#!/usr/bin/env bash

set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
RUNTIME_DIR="${LINEN_RUNTIME_DIR:-${ROOT_DIR}/.linen-runtime}"
CONFIG_PATH="${LINEN_CONFIG:-${ROOT_DIR}/dispatch.yaml}"
WORKSPACE_ROOT="${LINEN_WORKSPACE_ROOT:-${HOME}/.local/share/linen/workspaces}"
HOST="${LINEN_HOST:-127.0.0.1}"
PORT="${LINEN_PORT:-9000}"
SERVER_URL="${LINEN_SERVER_URL:-http://127.0.0.1:${PORT}}"
SKIP_DISPATCHER="${LINEN_SKIP_DISPATCHER:-0}"
SKIP_SYNC="${LINEN_SKIP_SYNC:-0}"

SERVER_PID_FILE="${RUNTIME_DIR}/server.pid"
DISPATCHER_PID_FILE="${RUNTIME_DIR}/dispatcher.pid"
SERVER_LOG="${RUNTIME_DIR}/server.log"
DISPATCHER_LOG="${RUNTIME_DIR}/dispatcher.log"
LINEN_BIN="${ROOT_DIR}/linen/.venv/bin/linen"

started_server=0
started_dispatcher=0

say() {
  printf '[linen] %s\n' "$*"
}

fail() {
  printf '[linen] error: %s\n' "$*" >&2
  exit 1
}

normalize_path() {
  local value="$1"
  if [[ "${value}" = /* ]]; then
    printf '%s\n' "${value}"
  else
    printf '%s\n' "${ROOT_DIR}/${value}"
  fi
}

CONFIG_PATH="$(normalize_path "${CONFIG_PATH}")"
RUNTIME_DIR="$(normalize_path "${RUNTIME_DIR}")"
WORKSPACE_ROOT="$(normalize_path "${WORKSPACE_ROOT}")"
SERVER_PID_FILE="${RUNTIME_DIR}/server.pid"
DISPATCHER_PID_FILE="${RUNTIME_DIR}/dispatcher.pid"
SERVER_LOG="${RUNTIME_DIR}/server.log"
DISPATCHER_LOG="${RUNTIME_DIR}/dispatcher.log"

read_pid() {
  local pid_file="$1"
  local pid
  [[ -r "${pid_file}" ]] || return 1
  pid="$(<"${pid_file}")"
  [[ "${pid}" =~ ^[0-9]+$ ]] || return 1
  printf '%s\n' "${pid}"
}

is_running() {
  local pid_file="$1"
  local role="$2"
  local pid
  local command_line
  pid="$(read_pid "${pid_file}")" || return 1
  kill -0 "${pid}" 2>/dev/null || return 1
  command_line="$(ps -p "${pid}" -o command= 2>/dev/null)" || return 1
  [[ "${command_line}" = *"${LINEN_BIN}"*" ${role}"* ]]
}

remove_stale_pid() {
  local pid_file="$1"
  local role="$2"
  if [[ -e "${pid_file}" ]] && ! is_running "${pid_file}" "${role}"; then
    rm -f "${pid_file}"
  fi
}

stop_process() {
  local name="$1"
  local pid_file="$2"
  local pid
  local role="${name}"
  [[ "${name}" = "server" ]] && role="serve"
  [[ "${name}" = "dispatcher" ]] && role="dispatch"

  if ! pid="$(read_pid "${pid_file}")" || ! is_running "${pid_file}" "${role}"; then
    rm -f "${pid_file}"
    say "${name} is not running"
    return
  fi

  say "stopping ${name} (pid ${pid})"
  kill "${pid}" 2>/dev/null || true
  for _ in {1..50}; do
    if ! kill -0 "${pid}" 2>/dev/null; then
      rm -f "${pid_file}"
      return
    fi
    sleep 0.1
  done

  say "${name} did not stop gracefully; terminating it"
  kill -KILL "${pid}" 2>/dev/null || true
  rm -f "${pid_file}"
}

cleanup_failed_start() {
  local status=$?
  if [[ ${status} -eq 0 ]]; then
    return
  fi
  if [[ ${started_dispatcher} -eq 1 ]]; then
    stop_process "dispatcher" "${DISPATCHER_PID_FILE}" || true
  fi
  if [[ ${started_server} -eq 1 ]]; then
    stop_process "server" "${SERVER_PID_FILE}" || true
  fi
  exit "${status}"
}

detect_worker() {
  if command -v claude >/dev/null 2>&1; then
    printf '%s %s\n' "claudecode" "claude"
  elif command -v codex >/dev/null 2>&1; then
    printf '%s %s\n' "codex" "codex"
  elif command -v pi >/dev/null 2>&1; then
    printf '%s %s\n' "pi" "pi"
  else
    return 1
  fi
}

create_config_if_missing() {
  local detected worker_type worker_name
  [[ "${SKIP_DISPATCHER}" = "1" ]] && return
  [[ -f "${CONFIG_PATH}" ]] && return

  detected="$(detect_worker)" || fail "no supported worker CLI found; install and authenticate claude, codex, or pi"
  worker_type="${detected%% *}"
  worker_name="${detected##* }"
  mkdir -p "$(dirname "${CONFIG_PATH}")" "${WORKSPACE_ROOT}"

  cat >"${CONFIG_PATH}" <<YAML
# Generated by ./deploy.sh. Existing files are never overwritten.
server: "${SERVER_URL}"

runtime:
  worker_healthcheck: disabled
  max_workers: 3
  max_running_projects: 2
  max_project_workers: 2
  interval: 3
  healthcheck_timeout: 15
  prompt_group: "default"

tasks:
  reason:
    timeout: 45
  explore:
    timeout: 600
    conclude_timeout: 120

local:
  workspace_root: "${WORKSPACE_ROOT}"
  completed_action: keep

workers:
  - name: "local-${worker_name}"
    type: "${worker_type}"
    task_types: [reason, explore]
    max_running: 1
    priority: 0
YAML
  say "created ${CONFIG_PATH} with ${worker_name} worker"
}

sync_dependencies() {
  if [[ "${SKIP_SYNC}" = "1" ]]; then
    [[ -x "${LINEN_BIN}" ]] || fail "${LINEN_BIN} does not exist; run without LINEN_SKIP_SYNC=1 first"
    return
  fi
  command -v uv >/dev/null 2>&1 || fail "uv is required; install it from https://docs.astral.sh/uv/"
  say "syncing Python dependencies"
  uv sync --project "${ROOT_DIR}/linen"
  [[ -x "${LINEN_BIN}" ]] || fail "linen executable was not created at ${LINEN_BIN}"
}

validate_config_server() {
  local configured_url
  [[ "${SKIP_DISPATCHER}" = "1" ]] && return
  configured_url="$("${ROOT_DIR}/linen/.venv/bin/python" - "${CONFIG_PATH}" <<'PY'
from pathlib import Path
import sys

import yaml

value = yaml.safe_load(Path(sys.argv[1]).read_text(encoding="utf-8")) or {}
print(value.get("server", ""))
PY
)"
  [[ -n "${configured_url}" ]] || fail "${CONFIG_PATH} does not define a server URL"
  if [[ "${configured_url%/}" != "${SERVER_URL%/}" ]]; then
    fail "config server ${configured_url} does not match deployment server ${SERVER_URL}; update ${CONFIG_PATH} or LINEN_SERVER_URL"
  fi
}

wait_for_server() {
  local pid="$1"
  local attempt
  for attempt in {1..60}; do
    if ! kill -0 "${pid}" 2>/dev/null; then
      tail -n 30 "${SERVER_LOG}" >&2 || true
      fail "server exited during startup"
    fi
    if curl --silent --show-error --fail --max-time 1 "${SERVER_URL}/" >/dev/null 2>&1; then
      return
    fi
    sleep 0.25
  done
  tail -n 30 "${SERVER_LOG}" >&2 || true
  fail "server did not become ready at ${SERVER_URL}"
}

start_server() {
  local pid
  remove_stale_pid "${SERVER_PID_FILE}" "serve"
  if is_running "${SERVER_PID_FILE}" "serve"; then
    say "server is already running (pid $(read_pid "${SERVER_PID_FILE}"))"
    return
  fi
  if curl --silent --fail --max-time 1 "${SERVER_URL}/" >/dev/null 2>&1; then
    fail "${SERVER_URL} is already serving another process"
  fi

  say "starting server"
  nohup "${LINEN_BIN}" serve \
    --host "${HOST}" \
    --port "${PORT}" \
    --workspace-root "${WORKSPACE_ROOT}" \
    >"${SERVER_LOG}" 2>&1 &
  pid=$!
  printf '%s\n' "${pid}" >"${SERVER_PID_FILE}"
  started_server=1
  wait_for_server "${pid}"
}

start_dispatcher() {
  local pid
  if [[ "${SKIP_DISPATCHER}" = "1" ]]; then
    say "dispatcher skipped (LINEN_SKIP_DISPATCHER=1)"
    return
  fi
  remove_stale_pid "${DISPATCHER_PID_FILE}" "dispatch"
  if is_running "${DISPATCHER_PID_FILE}" "dispatch"; then
    say "dispatcher is already running (pid $(read_pid "${DISPATCHER_PID_FILE}"))"
    return
  fi

  say "checking worker configuration"
  "${LINEN_BIN}" dispatch --config "${CONFIG_PATH}" --startup-healthcheck-only
  say "starting dispatcher"
  nohup "${LINEN_BIN}" dispatch --config "${CONFIG_PATH}" \
    >"${DISPATCHER_LOG}" 2>&1 &
  pid=$!
  printf '%s\n' "${pid}" >"${DISPATCHER_PID_FILE}"
  started_dispatcher=1
  sleep 0.5
  if ! kill -0 "${pid}" 2>/dev/null; then
    tail -n 30 "${DISPATCHER_LOG}" >&2 || true
    fail "dispatcher exited during startup"
  fi
}

start_all() {
  trap cleanup_failed_start EXIT
  mkdir -p "${RUNTIME_DIR}" "${WORKSPACE_ROOT}"
  command -v curl >/dev/null 2>&1 || fail "curl is required for the server readiness check"
  create_config_if_missing
  sync_dependencies
  validate_config_server
  start_server
  start_dispatcher
  trap - EXIT

  say "Linen is ready at ${SERVER_URL}"
  say "logs: ./deploy.sh logs"
  say "stop: ./deploy.sh stop"
}

stop_all() {
  stop_process "dispatcher" "${DISPATCHER_PID_FILE}"
  stop_process "server" "${SERVER_PID_FILE}"
}

show_status() {
  local failed=0
  if is_running "${SERVER_PID_FILE}" "serve"; then
    say "server: running (pid $(read_pid "${SERVER_PID_FILE}"), ${SERVER_URL})"
  else
    say "server: stopped"
    failed=1
  fi

  if [[ "${SKIP_DISPATCHER}" = "1" ]]; then
    say "dispatcher: skipped"
  elif is_running "${DISPATCHER_PID_FILE}" "dispatch"; then
    say "dispatcher: running (pid $(read_pid "${DISPATCHER_PID_FILE}"))"
  else
    say "dispatcher: stopped"
    failed=1
  fi
  return "${failed}"
}

show_logs() {
  mkdir -p "${RUNTIME_DIR}"
  touch "${SERVER_LOG}" "${DISPATCHER_LOG}"
  tail -n 100 -f "${SERVER_LOG}" "${DISPATCHER_LOG}"
}

usage() {
  cat <<'TEXT'
Usage: ./deploy.sh [start|stop|restart|status|logs]

Environment overrides:
  LINEN_HOST=127.0.0.1
  LINEN_PORT=9000
  LINEN_SERVER_URL=http://127.0.0.1:9000
  LINEN_CONFIG=./dispatch.yaml
  LINEN_WORKSPACE_ROOT=~/.local/share/linen/workspaces
  LINEN_RUNTIME_DIR=./.linen-runtime
  LINEN_SKIP_DISPATCHER=1
  LINEN_SKIP_SYNC=1
TEXT
}

case "${1:-start}" in
  start)
    start_all
    ;;
  stop)
    stop_all
    ;;
  restart)
    stop_all
    start_all
    ;;
  status)
    show_status
    ;;
  logs)
    show_logs
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
